# Generated by Django 2.0.7 on 2018-07-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='creator',
            field=models.CharField(default='', max_length=20, verbose_name='Username'),
        ),
    ]
