# Generated by Django 2.0.7 on 2018-07-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0002_url_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='url',
            name='creator_ip',
        ),
        migrations.AddField(
            model_name='url',
            name='category',
            field=models.CharField(default='Default', max_length=100),
        ),
        migrations.AddField(
            model_name='url',
            name='tags',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tags'),
        ),
    ]
